### ISSUE TITLE
Error in run_small_eady_problem.jl

### ISSUE THREAD

**Issue by navidcy** [glwagner/EadyTurbulence#4]
julia> include("run_small_eady_problem.jl")
ERROR: LoadError: UndefKeywordError: keyword argument schedule not assigned
Stacktrace:
 [1] top-level scope at /Users/navid/Research/EadyTurbulence/Oceananigans/run_small_eady_problem.jl:234
 [2] include(::String) at ./client.jl:457
 [3] top-level scope at REPL[4]:1
in expression starting at /Users/navid/Research/EadyTurbulence/Oceananigans/run_small_eady_problem.jl:234

**Comment by glwagner** [comment]
Ah, its out of date with the current version of Oceananigans. I'll fix it.

**Comment by navidcy** [comment]
But there is a Manifest.toml file there so it should have worked... I'm confused...

**Comment by glwagner** [comment]
the script is wrong

**Comment by glwagner** [comment]
The script went stale even though I updated packages in the Manifest

**Comment by navidcy** [comment]
Shall we work on the instability via power method? Is this the best place to start? (Would prefer to work together; more fun...)

**Comment by glwagner** [comment]
Let's! Opened #6 to discuss.
